
using SegResNetDS for training.
train:
  0%|          | 0/343 [00:04<?, ?it/s]
Traceback (most recent call last):
  File "/mnt/d/PROJECTION/TianChi/STS-2D/train.py", line 193, in <module>
    train_loss = train_step(train_loader, model, criterion, optimizer, CFG.device, epoch)
  File "/mnt/d/PROJECTION/TianChi/STS-2D/train.py", line 68, in train_step
    outputs = model(image.to(device))
  File "/home/zy/anaconda3/envs/kaggle_torch/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/d/PROJECTION/TianChi/STS-2D/models.py", line 93, in forward
    x = self.model(x)
  File "/home/zy/anaconda3/envs/kaggle_torch/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/zy/anaconda3/envs/kaggle_torch/lib/python3.9/site-packages/monai/networks/nets/segresnet_ds.py", line 430, in forward
    return self._forward(x)
  File "/home/zy/anaconda3/envs/kaggle_torch/lib/python3.9/site-packages/monai/networks/nets/segresnet_ds.py", line 400, in _forward
    x_down = self.encoder(x)
  File "/home/zy/anaconda3/envs/kaggle_torch/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/zy/anaconda3/envs/kaggle_torch/lib/python3.9/site-packages/monai/networks/nets/segresnet_ds.py", line 231, in forward
    return self._forward(x)
  File "/home/zy/anaconda3/envs/kaggle_torch/lib/python3.9/site-packages/monai/networks/nets/segresnet_ds.py", line 221, in _forward
    x = level["blocks"](x)
  File "/home/zy/anaconda3/envs/kaggle_torch/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/zy/anaconda3/envs/kaggle_torch/lib/python3.9/site-packages/torch/nn/modules/container.py", line 217, in forward
    input = module(input)
  File "/home/zy/anaconda3/envs/kaggle_torch/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/zy/anaconda3/envs/kaggle_torch/lib/python3.9/site-packages/monai/networks/nets/segresnet_ds.py", line 119, in forward
    x = self.conv1(self.act1(self.norm1(x)))
  File "/home/zy/anaconda3/envs/kaggle_torch/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/zy/anaconda3/envs/kaggle_torch/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/zy/anaconda3/envs/kaggle_torch/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: CUDA error: unknown error
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.