2023-06-15 16:30:16 WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f646b049310>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /api/4504800232407040/envelope/
2023-06-15 16:31:33 WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fee13caf6a0>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /api/4504800232407040/envelope/
2023-06-15 16:32:50 WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff02c336a60>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /api/4504800232407040/envelope/
2023-06-15 16:41:22 WARNING Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f646b027e80>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /api/4504800232407040/envelope/
2023-06-15 16:42:39 WARNING Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fee13cedaf0>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /api/4504800232407040/envelope/
2023-06-15 16:43:56 WARNING Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff02c426d30>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /api/4504800232407040/envelope/
2023-06-15 16:52:28 WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f646b0276d0>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /api/4504800232407040/envelope/
2023-06-15 16:53:44 WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fee13cede80>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /api/4504800232407040/envelope/
2023-06-15 16:55:01 WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff02c426100>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /api/4504800232407040/envelope/
2023-06-15 17:14:39 WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f646b027820>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /api/4504800232407040/envelope/
2023-06-15 17:15:56 WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fee13c80490>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /api/4504800232407040/envelope/
2023-06-15 17:17:12 WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff02c426a00>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /api/4504800232407040/envelope/
2023-06-15 17:25:44 WARNING Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f646b049760>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /api/4504800232407040/envelope/
2023-06-15 17:27:01 WARNING Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fee13c80520>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /api/4504800232407040/envelope/
2023-06-15 17:28:18 WARNING Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff02c4264f0>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /api/4504800232407040/envelope/
2023-06-15 17:36:50 WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f646b049640>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /api/4504800232407040/envelope/
2023-06-15 17:38:07 WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fee13c80280>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /api/4504800232407040/envelope/
2023-06-15 17:39:24 WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff02c4268e0>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /api/4504800232407040/envelope/
2023-09-13 03:45:42 ERROR dropped chunk HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/zhuangy/STS-2D/ctsvmls1/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fdb5861bcd0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
NoneType: None
2023-09-13 06:02:13 ERROR dropped chunk HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/zhuangy/STS-2D/ctsvmls1/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fdb30ffd220>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
NoneType: None
2023-09-13 08:20:46 ERROR dropped chunk HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/zhuangy/STS-2D/ctsvmls1/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fdb5806d2b0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
NoneType: None
2023-09-14 08:45:18 ERROR dropped chunk HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/zhuangy/STS-2D/yuqzorub/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc1fc57cac0>: Failed to establish a new connection: [Errno 111] Connection refused'))
NoneType: None
2023-09-14 22:35:35 WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f33c32d0280>: Failed to establish a new connection: [Errno 110] Connection timed out')': /api/4504800232407040/envelope/
2023-09-14 22:37:48 WARNING Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f33b1193ac0>: Failed to establish a new connection: [Errno 110] Connection timed out')': /api/4504800232407040/envelope/
