using regunet for training.
train:
  0%|          | 0/343 [00:02<?, ?it/s]
Traceback (most recent call last):
  File "/mnt/d/PROJECTION/TianChi/STS-2D/train.py", line 193, in <module>
    train_loss = train_step(train_loader, model, criterion, optimizer, CFG.device, epoch)
  File "/mnt/d/PROJECTION/TianChi/STS-2D/train.py", line 68, in train_step
    outputs = model(image.to(device))
  File "/home/zy/anaconda3/envs/kaggle_torch/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/d/PROJECTION/TianChi/STS-2D/models.py", line 41, in forward
    x = self.model(x)
  File "/home/zy/anaconda3/envs/kaggle_torch/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/zy/anaconda3/envs/kaggle_torch/lib/python3.9/site-packages/monai/networks/nets/regunet.py", line 216, in forward
    encoded = encode_pool(skip)
  File "/home/zy/anaconda3/envs/kaggle_torch/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/zy/anaconda3/envs/kaggle_torch/lib/python3.9/site-packages/monai/networks/blocks/regunet_block.py", line 168, in forward
    raise ValueError("expecting x spatial dimensions be even, " f"got x of shape {x.shape}")
ValueError: expecting x spatial dimensions be even, got x of shape torch.Size([64, 64, 5, 5])